import Head from "next/head"
import Center from "components/center"

function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>soldev.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center my={10}>{children}</Center>
      </main>
    </div>
  )
}

export default Layout
