import Head from "next/head"
import { UnorderedList, ListItem } from "@chakra-ui/react"
import Link from "next/link"

function CustomListItem({ href, ...props }) {
  return (
    <ListItem>
      <Link href={href} {...props} />
    </ListItem>
  )
}

function Index() {
  return (
    <UnorderedList>
      <CustomListItem href={"/1"}>01 - Read data from the Solana network</CustomListItem>
      <CustomListItem href={"/2"}>02 - Write data to the Solana network</CustomListItem>
    </UnorderedList>
  )
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>soldev.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Index></Index>
      </main>
    </div>
  )
}
